@MembershipPortal.API_HostAddress = http://localhost:5224



POST {{MembershipPortal.API_HostAddress}}/api/subscription/paginated?sortColumn=string&sortOrder=string&page=0&pageSize=0
Content-Type: application/json

{
        "id": 0,
        "subscriberId": 0,
        "productId": 0,
        "productName": "",
        "productPrice": ,
        "discountId": 0,
        "discountCode": "",
        "discountAmount": 0,
        "startDate": "",
        "expiryDate": "",
        "priceAfterDiscount": 0,
        "taxId": 0,
        "cgst": 0,
        "sgst": 0,
        "totalTaxPercentage": 0,
        "taxAmount": 0,
        "finalAmount": 0
}

###
